import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from './Navigation/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="bg-yellow-400 min-h-screen p-16 flex flex-1 flex-col justify-center items-center">
        <h1 className="">
          Welcome to
          <a className="text-blue-600 hover:bg-slate-100 hover:rounded-md p-2 hover:underline active:underline focus:underline" href="https://nextjs.org">
            Next.js!
          </a>
        </h1>

        <p className="">
          Get started by editing{' '}
          <code className="bg-gray-50 p-1">
            pages/index.tsx
          </code>
        </p>
      </main>

      <footer className="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
        <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 <a href="https://flowbite.com/" class="hover:underline">Flowbite™</a>. All Rights Reserved.
        </span>
        <ul className="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
          <li>
            <a href="#" className="mr-4 hover:underline md:mr-6 ">About</a>
          </li>
          <li>
            <a href="#" className="mr-4 hover:underline md:mr-6">Privacy Policy</a>
          </li>
          <li>
            <a href="#" className="mr-4 hover:underline md:mr-6">Licensing</a>
          </li>
          <li>
            <a href="#" className="hover:underline">Contact</a>
          </li>
        </ul>
      </footer>
    </div>
  )
}

export default Home
